inherited DMPedidoRapido: TDMPedidoRapido
  Left = 205
  Top = 41
  Height = 664
  Width = 1053
  inherited Q_Tabela: TIBQuery
    SQL.Strings = (
      'Select '#9't.Saida'#9#9'as IDMESTRE,'
      #9't.Favorecido'#9'as Favorecido,'
      #9't.Numero'#9'as Numero,'
      #9't.Data'#9#9'as Data,'
      #9't.Total'#9#9'as Total,'
      #9't.Situacao'#9'as Situacao,'
      #9't.OBS'#9#9'as OBS,'
      #9't.TipoMovimento'#9'as TipoMovimento,'
      #9't.PossuiTax'#9'as PossuiTax,'
      #9't.BaixaEstoque'#9'as BaixaEstoque,'
      #9't.CalcComissao'#9'as CalcComissao,'
      #9't.PossuiEntrega'#9'as PossuiEntrega,'
      #9't.TIPOPADRAO'#9'as TIPOPADRAO,'
      #9't.Tax'#9#9'as Tax,'
      #9't.PercentualTax'#9'as PercentualTax,'
      #9't.Desconto'#9'as Desconto,'
      #9't.PlanoPagamento'#9'as PlanoPagamento,'
      #9't.Vendedor'#9'as Vendedor,'
      #9't.Frete'#9#9'as Frete,'
      #9't.TipoEntrega'#9'as TipoEntrega,'
      #9't.DataEntrega'#9'as DataEntrega,'
      #9't.Pedido_Cliente'#9'as Pedido_Cliente,'
      #9't.OutrasDespesas'#9'as OutrasDespesas,'
      #9't.Juros'#9#9'as Juros,'
      #9't.Campo01'#9'as Campo01,'
      #9't.Campo02'#9'as Campo02,'
      #9't.Campo03 '#9'as Campo03,'
      #9't.Campo04'#9'as Campo04,'
      #9't.Impresso'#9'as Impresso,'
      #9't.Imposto'#9#9'as Imposto,'
      #9't.Imposto_Incluso'#9'as Imposto_Incluso,'
      #9't.PComissao'#9'as PComissao,'#9
      #9't.TabelaPadrao'#9'as TabelaPadrao,'
      #9't.PJuros'#9#9'as PJuros,'
      #9't.TotalItens'#9'as TotalItens,'
      #9't.TotalItens123'#9'as TotalItens123,'
      #9't.VALIDADE'#9'as Validade,'
      #9't.CondicoesPgto'#9'as CondicoesPgto,'
      #9't.DataEntregue'#9'as DataEntregue,'
      #9't.Status'#9#9'as Status,'
      #9't.BaseImposto'#9'as BaseImposto,'
      #9't.BaseIncluso'#9'as BaseIncluso,'
      #9't.DescontoItens'#9'as DescontoItens,'
      #9't.Total'#9#9'as TotalOld,'
      #9't.LocalEntrega'#9'as LocalEntrega,'
      #9't.Caixa'#9#9'as Caixa,'
      #9't.TipoImpressao'#9'as TipoImpressao,'
      #9't.Status'#9#9'as StatusOld,'
      #9't.ReducoesBase'#9'as ReducoesBase,'
      #9't.AcrescimosBase'#9'as AcrescimosBase,'
      #9't.Volumes'#9#9'as Volumes,'
      #9't.TermoContrato'#9'as TermoContrato,'
      #9't.Desconto'#9'as OldDesconto,'
      #9't.AlmoxPadrao'#9'as AlmoxPadrao,'
      #9't.PJurosNegociado'#9'as PJurosNegociado,'
      #9't.TotalProdutos'#9'as TotalProdutos,'
      #9't.VALORIPIITENS,'
      #9't.BaseCalcICMSItens,'
      #9't.BaseCalcSubstItens,'
      #9't.ValorICMSItens,'
      #9't.CFOPNOTA ,'
      #9't.SERIENOTA ,'
      #9't.UFDESTINO ,'
      #9't.BASECALCICMS ,'
      #9't.VALORICMS ,'
      #9't.VALORISS ,'
      #9't.VALORIPI ,'
      #9't.BASECALCSUBST ,'
      #9't.VALORICMSSUBST ,'
      #9't.ALIQICMSVENDA ,'
      #9't.VALORISENTAS ,'
      #9't.TOTALSERVICOS ,'
      #9't.POSSUIICMS ,'
      #9't.POSSUIIPI ,'
      #9't.POSSUIISS ,'
      #9't.CONTABILIZAICMS ,'
      #9't.VALOROUTRASICMS ,'
      #9't.MODELO,'
      #9't.PDV,'
      #9't.FONTE,'
      #9't.VALORSEGURO,'
      #9't.TIPOFRETE,'
      #9't.TRANSPORTADORA,'
      #9't.PESOBRUTO,'
      #9't.PESOLIQUIDO,'
      #9't.DESCESPECIE,'
      #9't.DESCMARCA,'
      #9't.DESCNUMERO,'
      #9't.PLACAVEIC,'
      #9't.SUBSTTRIB,'
      #9't.ATRATAR ,'
      #9't.INTRODUCAO ,'
      #9't.PRAZOENTREGA ,'
      #9't.CONDICOESPAGTO ,'
      #9't.GARANTIA ,'
      #9't.SEESTOQUE ,'
      #9't.PROCESSO ,'
      #9't.CARTACONVITE ,'
      #9't.TOMADAPRECOS ,'
      #9't.DATAABERTURA ,'
      #9't.EXPLICACOES ,'
      #9't.LICITACAOICMS ,'
      #9't.BAIXAESTOQUEFISCAL, '
      '                t.mensagemitem,'
      '                T.IMPORTACAO,'
      #9'f.CODIGO            '#9'as F_CODIGO,'
      #9'f.NOME              '#9'as F_NOME,'
      #9'f.RAZAO             '#9'as F_RAZAO,'
      #9'f.ENDERECO       '#9'as F_ENDERECO,'
      #9'f.CIDADE            '#9'as F_CIDADE,'
      #9'f.UF                '#9'as F_UF,'
      #9'f.CEP               '#9'as F_CEP,'
      #9'f.CAIXAPOSTAL    '#9'as F_CAIXAPOSTAL,'
      #9'f.PAIS              '#9'as F_PAIS,'
      #9'f.FONE1             '#9'as F_FONE1,'
      #9'f.FONE2             '#9'as F_FONE2,'
      #9'f.FAX               '#9'as F_FAX,'
      #9'f.CELULAR           '#9'as F_CELULAR,'
      #9'f.CONTATO           '#9'as F_CONTATO,'
      #9'f.EMAIL             '#9'as F_EMAIL,'
      #9'f.TIPOFAVORECIDO    '#9'as F_TIPOFAVORECIDO,'
      #9'f.TIPOATIVIDADE     '#9'as F_TIPOATIVIDADE,'
      #9'f.PLANOPAGAMENTO    '#9'as F_PLANOPAGAMENTO,'
      #9'f.VENDEDOR          '#9'as F_VENDEDOR,'
      #9'f.LIMITECREDITO     '#9'as F_LIMITECREDITO,'
      #9'f.TAXAVEL           '#9'as F_TAXAVEL,'
      #9'f.TAX               '#9'as F_TAX,'
      #9'f.EIN               '#9'as F_EIN,'
      #9'f.SSN               '#9'as F_SSN,'
      #9'f.TABELAPRECO  '#9'as F_TABELAPRECO,'
      #9'f.DESATIVADO     '#9'as F_DESATIVADO,'
      #9'f.EXIGIVEL1099   '#9'as F_EXIGIVEL1099,'
      #9'f.TIPOENTREGA    '#9'as F_TIPOENTREGA,'
      #9'f.DATACADASTRO'#9'as F_DATACADASTRO,'
      #9'f.SITE              '#9'as F_SITE,'
      #9'f.OBS               '#9'as F_OBS,'
      #9'f.IMPORTACAO   '#9'as F_IMPORTACAO,'
      #9'f.SITUACAO      '#9'as F_SITUACAO,'
      #9'f.CARGO           '#9'as F_CARGO,'
      #9'f.LOGOTIPO     '#9'as F_LOGOTIPO,'
      #9'f.JUROSFACTORY'#9'as F_JUROSFACTORY,'
      #9'f.TAXASFACTORY'#9'as F_TAXASFACTORY,'
      #9'f.FLOATINGFACTORY   as F_FLOATINGFACTORY,'
      #9'f.MEMO_CHECK  '#9'as F_MEMO_CHECK,'
      #9'f.CREDITO           '#9'as F_CREDITO,'
      #9'f.CONTA             '#9'as F_CONTA,'
      #9'f.NUMERO_REVENDA    as F_NUMERO_REVENDA,'
      #9'f.TIPO_FUNC         '#9'as F_TIPO_FUNC,'
      #9'f.DATANASC     '#9'as F_DATANASC,'
      #9'f.COMISSAO '#9'as F_COMISSAO,'
      #9'f.AgruparPorItem'#9'as F_AgruparPorItem,'
      #9'f.BAIRRO                as F_BAIRRO,'
      #9'f.CPF_CNPJ            as F_CPF_CNPJ,'
      #9'f.INSCRICAO_EST as F_INSCRICAO_EST,'
      #9'f.PERCDESCONTO as F_PERCDESCONTO,'
      '                f.ConsumidorFinal    as F_ConsumidorFinal,'
      #9'tm.DESCRICAO'#9'as TM_Descricao,'
      #9'tm.TIPO'#9#9'as TM_TIPO,'
      #9'tm.POSSUITAX'#9'as TM_PossuiTax,'
      #9'tm.BAIXAESTOQUE as TM_BaixaEstoque,'
      #9'tm.BAIXAESTOQUEFISCAL as TM_BaixaEstoqueFiscal,'
      #9'tm.GERAFINANCEIRO AS TM_GeraFinanceiro,'
      #9'tm.CALCCOMISSAO as TM_CalcComissao,'
      #9'tm.POSSUIENTREGA as TM_PossuiEntrega,'
      #9'tm.BLOQUEARSEATRASADO as TM_BloquearSeAtrasado,'
      #9'tm.BLOQUEARPORSITUACAO as TM_BloquearPorSituacao,'
      #9'tm.BLOQUEARPORESTOQUE as TM_BloquearPorEstoque,'
      #9'tm.LIMITEFAVORECIDO as TM_LimiteFavorecido,'
      #9'tm.SIGLAINICIAL '#9'as TM_SiglaInicial,'
      #9't.TotalPgtos '#9'as  PagoInvoice,'
      #9't.COBRANCA          as  COBRANCA,'
      #9't.CARTEIRA            as  CARTEIRA,'
      #9't.NF_CUPOM           as NF_CUPOM,'
      #9't.MEDICO                 as MEDICO,'
      '                t.EMPRESA'
      
        'from '#9'(SAIDAS t  left join FAVORECIDOS f on t.FAVORECIDO = f.FAV' +
        'ORECIDO)'
      
        #9'left join TIPOSMOVIMENTO tm on tm.TIPOMOVIMENTO = T.TIPOMOVIMEN' +
        'TO')
  end
  inherited U_Tabela: TIBUpdateSQL
    RefreshSQL.Strings = (
      'Select '
      '  EMPRESA,'
      '  SAIDA,'
      '  PDV,'
      '  NUMERO,'
      '  DATA,'
      '  FAVORECIDO,'
      '  OBS,'
      '  TAX,'
      '  PERCENTUALTAX,'
      '  DESCONTO,'
      '  PLANOPAGAMENTO,'
      '  VENDEDOR,'
      '  FRETE,'
      '  TOTAL,'
      '  TIPOENTREGA,'
      '  DATAENTREGA,'
      '  IMPORTACAO,'
      '  SITUACAO,'
      '  TIPOMOVIMENTO,'
      '  PEDIDO_CLIENTE,'
      '  OUTRASDESPESAS,'
      '  JUROS,'
      '  POSSUITAX,'
      '  BAIXAESTOQUE,'
      '  CALCCOMISSAO,'
      '  POSSUIENTREGA,'
      '  CAMPO01,'
      '  CAMPO02,'
      '  CAMPO03,'
      '  CAMPO04,'
      '  IMPRESSO,'
      '  IMPOSTO,'
      '  IMPOSTO_INCLUSO,'
      '  PCOMISSAO,'
      '  CAIXA,'
      '  LOCALENTREGA,'
      '  TABELAPADRAO,'
      '  TIPOPADRAO,'
      '  DATACANCELAMENTO,'
      '  FUNCCANCELAMENTO,'
      '  MOTIVOCANCELAMENTO,'
      '  PJUROS,'
      '  VALORCOMISSAO,'
      '  TOTALITENS,'
      '  VALIDADE,'
      '  CONDICOESPGTO,'
      '  DATAENTREGUE,'
      '  STATUS,'
      '  TOTALITENS123,'
      '  BASEIMPOSTO,'
      '  BASEINCLUSO,'
      '  DESCONTOITENS,'
      '  TIPOIMPRESSAO,'
      '  TOTALPGTOS,'
      '  STATUSANTERIOR,'
      '  REDUCOESBASE,'
      '  ACRESCIMOSBASE,'
      '  DTMODIFICACAO,'
      '  VOLUMES,'
      '  TERMOCONTRATO,'
      '  ALMOXPADRAO,'
      '  CFOPNOTA,'
      '  SERIENOTA,'
      '  UFDESTINO,'
      '  BASECALCICMS,'
      '  VALORICMS,'
      '  VALORISS,'
      '  VALORIPI,'
      '  BASECALCSUBST,'
      '  VALORICMSSUBST,'
      '  VALORSEGURO,'
      '  TIPOFRETE,'
      '  TRANSPORTADORA,'
      '  PESOBRUTO,'
      '  PESOLIQUIDO,'
      '  ALIQICMSVENDA,'
      '  VALORISENTAS,'
      '  TOTALSERVICOS,'
      '  DESCESPECIE,'
      '  DESCMARCA,'
      '  DESCNUMERO,'
      '  INDICADOPELOFAV,'
      '  POSSUIICMS,'
      '  POSSUIIPI,'
      '  POSSUIISS,'
      '  CONTABILIZAICMS,'
      '  MODELO,'
      '  VALOROUTRASICMS,'
      '  VALORISENTASIPI,'
      '  VALOROUTRASIPI,'
      '  FONTE,'
      '  PLACAVEIC,'
      '  ATRATAR,'
      '  INTRODUCAO,'
      '  PRAZOENTREGA,'
      '  GARANTIA,'
      '  SEESTOQUE,'
      '  PROCESSO,'
      '  CARTACONVITE,'
      '  TOMADAPRECOS,'
      '  DATAABERTURA,'
      '  EXPLICACOES,'
      '  LICITACAOICMS,'
      '  SUBSTTRIB,'
      '  PJUROSNEGOCIADO,'
      '  CONDICOESPAGTO,'
      '  TOTALPRODUTOS,'
      '  VALORIPIITENS,'
      '  BASECALCICMSITENS,'
      '  VALORICMSITENS,'
      '  BASECALCSUBSTITENS,'
      '  COBRANCA,'
      '  CARTEIRA,'
      '  MEDICO,'
      '  NF_CUPOM,'
      '  DEVOLUCAO,'
      '  BAIXAESTOQUEFISCAL,'
      '  HORA,'
      '  MENSAGEMITEM,'
      '  NUMEROSERIEECF,'
      '  NUMEROECF,'
      '  CCF,'
      '  CRZ,'
      '  DETALHEIMPORTACAO'
      'from SAIDAS '
      'where'
      '  EMPRESA = :EMPRESA and'
      '  SAIDA = :SAIDA and'
      '  PDV = :PDV and'
      '  NUMERO = :NUMERO and'
      '  DATA = :DATA and'
      '  FAVORECIDO = :FAVORECIDO and'
      '  OBS = :OBS and'
      '  TAX = :TAX and'
      '  PERCENTUALTAX = :PERCENTUALTAX and'
      '  DESCONTO = :DESCONTO and'
      '  PLANOPAGAMENTO = :PLANOPAGAMENTO and'
      '  VENDEDOR = :VENDEDOR and'
      '  FRETE = :FRETE and'
      '  TOTAL = :TOTAL and'
      '  TIPOENTREGA = :TIPOENTREGA and'
      '  DATAENTREGA = :DATAENTREGA and'
      '  IMPORTACAO = :IMPORTACAO and'
      '  SITUACAO = :SITUACAO and'
      '  TIPOMOVIMENTO = :TIPOMOVIMENTO and'
      '  PEDIDO_CLIENTE = :PEDIDO_CLIENTE and'
      '  OUTRASDESPESAS = :OUTRASDESPESAS and'
      '  JUROS = :JUROS and'
      '  POSSUITAX = :POSSUITAX and'
      '  BAIXAESTOQUE = :BAIXAESTOQUE and'
      '  CALCCOMISSAO = :CALCCOMISSAO and'
      '  POSSUIENTREGA = :POSSUIENTREGA and'
      '  CAMPO01 = :CAMPO01 and'
      '  CAMPO02 = :CAMPO02 and'
      '  CAMPO03 = :CAMPO03 and'
      '  CAMPO04 = :CAMPO04 and'
      '  IMPRESSO = :IMPRESSO and'
      '  IMPOSTO = :IMPOSTO and'
      '  IMPOSTO_INCLUSO = :IMPOSTO_INCLUSO and'
      '  PCOMISSAO = :PCOMISSAO and'
      '  CAIXA = :CAIXA and'
      '  LOCALENTREGA = :LOCALENTREGA and'
      '  TABELAPADRAO = :TABELAPADRAO and'
      '  TIPOPADRAO = :TIPOPADRAO and'
      '  DATACANCELAMENTO = :DATACANCELAMENTO and'
      '  FUNCCANCELAMENTO = :FUNCCANCELAMENTO and'
      '  MOTIVOCANCELAMENTO = :MOTIVOCANCELAMENTO and'
      '  PJUROS = :PJUROS and'
      '  VALORCOMISSAO = :VALORCOMISSAO and'
      '  TOTALITENS = :TOTALITENS and'
      '  VALIDADE = :VALIDADE and'
      '  CONDICOESPGTO = :CONDICOESPGTO and'
      '  DATAENTREGUE = :DATAENTREGUE and'
      '  STATUS = :STATUS and'
      '  TOTALITENS123 = :TOTALITENS123 and'
      '  BASEIMPOSTO = :BASEIMPOSTO and'
      '  BASEINCLUSO = :BASEINCLUSO and'
      '  DESCONTOITENS = :DESCONTOITENS and'
      '  TIPOIMPRESSAO = :TIPOIMPRESSAO and'
      '  TOTALPGTOS = :TOTALPGTOS and'
      '  STATUSANTERIOR = :STATUSANTERIOR and'
      '  REDUCOESBASE = :REDUCOESBASE and'
      '  ACRESCIMOSBASE = :ACRESCIMOSBASE and'
      '  DTMODIFICACAO = :DTMODIFICACAO and'
      '  VOLUMES = :VOLUMES and'
      '  TERMOCONTRATO = :TERMOCONTRATO and'
      '  ALMOXPADRAO = :ALMOXPADRAO and'
      '  CFOPNOTA = :CFOPNOTA and'
      '  SERIENOTA = :SERIENOTA and'
      '  UFDESTINO = :UFDESTINO and'
      '  BASECALCICMS = :BASECALCICMS and'
      '  VALORICMS = :VALORICMS and'
      '  VALORISS = :VALORISS and'
      '  VALORIPI = :VALORIPI and'
      '  BASECALCSUBST = :BASECALCSUBST and'
      '  VALORICMSSUBST = :VALORICMSSUBST and'
      '  VALORSEGURO = :VALORSEGURO and'
      '  TIPOFRETE = :TIPOFRETE and'
      '  TRANSPORTADORA = :TRANSPORTADORA and'
      '  PESOBRUTO = :PESOBRUTO and'
      '  PESOLIQUIDO = :PESOLIQUIDO and'
      '  ALIQICMSVENDA = :ALIQICMSVENDA and'
      '  VALORISENTAS = :VALORISENTAS and'
      '  TOTALSERVICOS = :TOTALSERVICOS and'
      '  DESCESPECIE = :DESCESPECIE and'
      '  DESCMARCA = :DESCMARCA and'
      '  DESCNUMERO = :DESCNUMERO and'
      '  INDICADOPELOFAV = :INDICADOPELOFAV and'
      '  POSSUIICMS = :POSSUIICMS and'
      '  POSSUIIPI = :POSSUIIPI and'
      '  POSSUIISS = :POSSUIISS and'
      '  CONTABILIZAICMS = :CONTABILIZAICMS and'
      '  MODELO = :MODELO and'
      '  VALOROUTRASICMS = :VALOROUTRASICMS and'
      '  VALORISENTASIPI = :VALORISENTASIPI and'
      '  VALOROUTRASIPI = :VALOROUTRASIPI and'
      '  FONTE = :FONTE and'
      '  PLACAVEIC = :PLACAVEIC and'
      '  ATRATAR = :ATRATAR and'
      '  INTRODUCAO = :INTRODUCAO and'
      '  PRAZOENTREGA = :PRAZOENTREGA and'
      '  GARANTIA = :GARANTIA and'
      '  SEESTOQUE = :SEESTOQUE and'
      '  PROCESSO = :PROCESSO and'
      '  CARTACONVITE = :CARTACONVITE and'
      '  TOMADAPRECOS = :TOMADAPRECOS and'
      '  DATAABERTURA = :DATAABERTURA and'
      '  EXPLICACOES = :EXPLICACOES and'
      '  LICITACAOICMS = :LICITACAOICMS and'
      '  SUBSTTRIB = :SUBSTTRIB and'
      '  PJUROSNEGOCIADO = :PJUROSNEGOCIADO and'
      '  CONDICOESPAGTO = :CONDICOESPAGTO and'
      '  TOTALPRODUTOS = :TOTALPRODUTOS and'
      '  VALORIPIITENS = :VALORIPIITENS and'
      '  BASECALCICMSITENS = :BASECALCICMSITENS and'
      '  VALORICMSITENS = :VALORICMSITENS and'
      '  BASECALCSUBSTITENS = :BASECALCSUBSTITENS and'
      '  COBRANCA = :COBRANCA and'
      '  CARTEIRA = :CARTEIRA and'
      '  MEDICO = :MEDICO and'
      '  NF_CUPOM = :NF_CUPOM and'
      '  DEVOLUCAO = :DEVOLUCAO and'
      '  BAIXAESTOQUEFISCAL = :BAIXAESTOQUEFISCAL and'
      '  HORA = :HORA and'
      '  MENSAGEMITEM = :MENSAGEMITEM and'
      '  NUMEROSERIEECF = :NUMEROSERIEECF and'
      '  NUMEROECF = :NUMEROECF and'
      '  CCF = :CCF and'
      '  CRZ = :CRZ and'
      '  DETALHEIMPORTACAO = :DETALHEIMPORTACAO')
    ModifySQL.Strings = (
      'update SAIDAS'
      'set'
      '  EMPRESA = :EMPRESA,'
      '  PDV = :PDV,'
      '  NUMERO = :NUMERO,'
      '  DATA = :DATA,'
      '  FAVORECIDO = :FAVORECIDO,'
      '  OBS = :OBS,'
      '  TAX = :TAX,'
      '  PERCENTUALTAX = :PERCENTUALTAX,'
      '  DESCONTO = :DESCONTO,'
      '  PLANOPAGAMENTO = :PLANOPAGAMENTO,'
      '  VENDEDOR = :VENDEDOR,'
      '  FRETE = :FRETE,'
      '  TOTAL = :TOTAL,'
      '  TIPOENTREGA = :TIPOENTREGA,'
      '  DATAENTREGA = :DATAENTREGA,'
      '  IMPORTACAO = :IMPORTACAO,'
      '  SITUACAO = :SITUACAO,'
      '  TIPOMOVIMENTO = :TIPOMOVIMENTO,'
      '  PEDIDO_CLIENTE = :PEDIDO_CLIENTE,'
      '  OUTRASDESPESAS = :OUTRASDESPESAS,'
      '  JUROS = :JUROS,'
      '  POSSUITAX = :POSSUITAX,'
      '  BAIXAESTOQUE = :BAIXAESTOQUE,'
      '  CALCCOMISSAO = :CALCCOMISSAO,'
      '  POSSUIENTREGA = :POSSUIENTREGA,'
      '  CAMPO01 = :CAMPO01,'
      '  CAMPO02 = :CAMPO02,'
      '  CAMPO03 = :CAMPO03,'
      '  CAMPO04 = :CAMPO04,'
      '  IMPRESSO = :IMPRESSO,'
      '  IMPOSTO = :IMPOSTO,'
      '  IMPOSTO_INCLUSO = :IMPOSTO_INCLUSO,'
      '  PCOMISSAO = :PCOMISSAO,'
      '  CAIXA = :CAIXA,'
      '  LOCALENTREGA = :LOCALENTREGA,'
      '  TABELAPADRAO = :TABELAPADRAO,'
      '  TIPOPADRAO = :TIPOPADRAO,'
      '  DATACANCELAMENTO = :DATACANCELAMENTO,'
      '  FUNCCANCELAMENTO = :FUNCCANCELAMENTO,'
      '  MOTIVOCANCELAMENTO = :MOTIVOCANCELAMENTO,'
      '  PJUROS = :PJUROS,'
      '  VALORCOMISSAO = :VALORCOMISSAO,'
      '  TOTALITENS = :TOTALITENS,'
      '  VALIDADE = :VALIDADE,'
      '  CONDICOESPGTO = :CONDICOESPGTO,'
      '  DATAENTREGUE = :DATAENTREGUE,'
      '  STATUS = :STATUS,'
      '  TOTALITENS123 = :TOTALITENS123,'
      '  BASEIMPOSTO = :BASEIMPOSTO,'
      '  BASEINCLUSO = :BASEINCLUSO,'
      '  DESCONTOITENS = :DESCONTOITENS,'
      '  TIPOIMPRESSAO = :TIPOIMPRESSAO,'
      '  TOTALPGTOS = :TOTALPGTOS,'
      '  STATUSANTERIOR = :STATUSANTERIOR,'
      '  REDUCOESBASE = :REDUCOESBASE,'
      '  ACRESCIMOSBASE = :ACRESCIMOSBASE,'
      '  DTMODIFICACAO = :DTMODIFICACAO,'
      '  VOLUMES = :VOLUMES,'
      '  TERMOCONTRATO = :TERMOCONTRATO,'
      '  ALMOXPADRAO = :ALMOXPADRAO,'
      '  CFOPNOTA = :CFOPNOTA,'
      '  SERIENOTA = :SERIENOTA,'
      '  UFDESTINO = :UFDESTINO,'
      '  BASECALCICMS = :BASECALCICMS,'
      '  VALORICMS = :VALORICMS,'
      '  VALORISS = :VALORISS,'
      '  VALORIPI = :VALORIPI,'
      '  BASECALCSUBST = :BASECALCSUBST,'
      '  VALORICMSSUBST = :VALORICMSSUBST,'
      '  VALORSEGURO = :VALORSEGURO,'
      '  TIPOFRETE = :TIPOFRETE,'
      '  TRANSPORTADORA = :TRANSPORTADORA,'
      '  PESOBRUTO = :PESOBRUTO,'
      '  PESOLIQUIDO = :PESOLIQUIDO,'
      '  ALIQICMSVENDA = :ALIQICMSVENDA,'
      '  VALORISENTAS = :VALORISENTAS,'
      '  TOTALSERVICOS = :TOTALSERVICOS,'
      '  DESCESPECIE = :DESCESPECIE,'
      '  DESCMARCA = :DESCMARCA,'
      '  DESCNUMERO = :DESCNUMERO,'
      '  INDICADOPELOFAV = :INDICADOPELOFAV,'
      '  POSSUIICMS = :POSSUIICMS,'
      '  POSSUIIPI = :POSSUIIPI,'
      '  POSSUIISS = :POSSUIISS,'
      '  CONTABILIZAICMS = :CONTABILIZAICMS,'
      '  MODELO = :MODELO,'
      '  VALOROUTRASICMS = :VALOROUTRASICMS,'
      '  VALORISENTASIPI = :VALORISENTASIPI,'
      '  VALOROUTRASIPI = :VALOROUTRASIPI,'
      '  FONTE = :FONTE,'
      '  PLACAVEIC = :PLACAVEIC,'
      '  ATRATAR = :ATRATAR,'
      '  INTRODUCAO = :INTRODUCAO,'
      '  PRAZOENTREGA = :PRAZOENTREGA,'
      '  GARANTIA = :GARANTIA,'
      '  SEESTOQUE = :SEESTOQUE,'
      '  PROCESSO = :PROCESSO,'
      '  CARTACONVITE = :CARTACONVITE,'
      '  TOMADAPRECOS = :TOMADAPRECOS,'
      '  DATAABERTURA = :DATAABERTURA,'
      '  EXPLICACOES = :EXPLICACOES,'
      '  LICITACAOICMS = :LICITACAOICMS,'
      '  SUBSTTRIB = :SUBSTTRIB,'
      '  PJUROSNEGOCIADO = :PJUROSNEGOCIADO,'
      '  CONDICOESPAGTO = :CONDICOESPAGTO,'
      '  TOTALPRODUTOS = :TOTALPRODUTOS,'
      '  VALORIPIITENS = :VALORIPIITENS,'
      '  BASECALCICMSITENS = :BASECALCICMSITENS,'
      '  VALORICMSITENS = :VALORICMSITENS,'
      '  BASECALCSUBSTITENS = :BASECALCSUBSTITENS,'
      '  COBRANCA = :COBRANCA,'
      '  CARTEIRA = :CARTEIRA,'
      '  MEDICO = :MEDICO,'
      '  NF_CUPOM = :NF_CUPOM,'
      '  DEVOLUCAO = :DEVOLUCAO,'
      '  BAIXAESTOQUEFISCAL = :BAIXAESTOQUEFISCAL,'
      '  HORA = :HORA,'
      '  MENSAGEMITEM = :MENSAGEMITEM,'
      '  NUMEROSERIEECF = :NUMEROSERIEECF,'
      '  NUMEROECF = :NUMEROECF,'
      '  CCF = :CCF,'
      '  CRZ = :CRZ,'
      '  DETALHEIMPORTACAO = :DETALHEIMPORTACAO'
      'where'
      '  SAIDA = :OLD_SAIDA '
      '  ')
    InsertSQL.Strings = (
      'insert into SAIDAS'
      '  (EMPRESA, SAIDA ,PDV, NUMERO, DATA, FAVORECIDO, OBS, TAX, '
      'PERCENTUALTAX, '
      '   DESCONTO, PLANOPAGAMENTO, VENDEDOR, FRETE, TOTAL, '
      'TIPOENTREGA, DATAENTREGA, '
      '   IMPORTACAO, SITUACAO, TIPOMOVIMENTO, PEDIDO_CLIENTE, '
      'OUTRASDESPESAS, '
      '   JUROS, POSSUITAX, BAIXAESTOQUE, CALCCOMISSAO, POSSUIENTREGA, '
      'CAMPO01, '
      
        '   CAMPO02, CAMPO03, CAMPO04, IMPRESSO, IMPOSTO, IMPOSTO_INCLUSO' +
        ', '
      'PCOMISSAO, '
      '   CAIXA, LOCALENTREGA, TABELAPADRAO, TIPOPADRAO, '
      'DATACANCELAMENTO, FUNCCANCELAMENTO, '
      '   MOTIVOCANCELAMENTO, PJUROS, VALORCOMISSAO, TOTALITENS, '
      'VALIDADE, CONDICOESPGTO, '
      
        '   DATAENTREGUE, STATUS, TOTALITENS123, BASEIMPOSTO, BASEINCLUSO' +
        ', '
      'DESCONTOITENS, '
      '   TIPOIMPRESSAO, TOTALPGTOS, STATUSANTERIOR, REDUCOESBASE, '
      'ACRESCIMOSBASE, '
      '   DTMODIFICACAO, VOLUMES, TERMOCONTRATO, ALMOXPADRAO, '
      'CFOPNOTA, SERIENOTA, '
      '   UFDESTINO, BASECALCICMS, VALORICMS, VALORISS, VALORIPI, '
      'BASECALCSUBST, '
      '   VALORICMSSUBST, VALORSEGURO, TIPOFRETE, TRANSPORTADORA, '
      'PESOBRUTO, PESOLIQUIDO, '
      '   ALIQICMSVENDA, VALORISENTAS, TOTALSERVICOS, DESCESPECIE, '
      'DESCMARCA, '
      
        '   DESCNUMERO, INDICADOPELOFAV, POSSUIICMS, POSSUIIPI, POSSUIISS' +
        ', '
      'CONTABILIZAICMS, '
      '   MODELO, VALOROUTRASICMS, VALORISENTASIPI, VALOROUTRASIPI, '
      'FONTE, PLACAVEIC, '
      '   ATRATAR, INTRODUCAO, PRAZOENTREGA, GARANTIA, SEESTOQUE, '
      'PROCESSO, CARTACONVITE, '
      '   TOMADAPRECOS, DATAABERTURA, EXPLICACOES, LICITACAOICMS, '
      'SUBSTTRIB, PJUROSNEGOCIADO, '
      '   CONDICOESPAGTO, TOTALPRODUTOS, VALORIPIITENS, '
      'BASECALCICMSITENS, VALORICMSITENS, '
      '   BASECALCSUBSTITENS, COBRANCA, CARTEIRA, MEDICO, NF_CUPOM, '
      'DEVOLUCAO, '
      '   BAIXAESTOQUEFISCAL, HORA, MENSAGEMITEM, NUMEROSERIEECF, '
      'NUMEROECF, CCF, '
      '   CRZ, DETALHEIMPORTACAO)'
      'values'
      
        '  (:EMPRESA,:IDMESTRE, :PDV, :NUMERO, :DATA, :FAVORECIDO, :OBS, ' +
        ':TAX, '
      ':PERCENTUALTAX, '
      '   :DESCONTO, :PLANOPAGAMENTO, :VENDEDOR, :FRETE, :TOTAL, '
      ':TIPOENTREGA, '
      '   :DATAENTREGA, :IMPORTACAO, :SITUACAO, :TIPOMOVIMENTO, '
      ':PEDIDO_CLIENTE, '
      '   :OUTRASDESPESAS, :JUROS, :POSSUITAX, :BAIXAESTOQUE, '
      ':CALCCOMISSAO, :POSSUIENTREGA, '
      '   :CAMPO01, :CAMPO02, :CAMPO03, :CAMPO04, :IMPRESSO, :IMPOSTO, '
      ':IMPOSTO_INCLUSO, '
      
        '   :PCOMISSAO, :CAIXA, :LOCALENTREGA, :TABELAPADRAO, :TIPOPADRAO' +
        ', '
      ':DATACANCELAMENTO, '
      '   :FUNCCANCELAMENTO, :MOTIVOCANCELAMENTO, :PJUROS, '
      ':VALORCOMISSAO, :TOTALITENS, '
      '   :VALIDADE, :CONDICOESPGTO, :DATAENTREGUE, :STATUS, '
      ':TOTALITENS123, :BASEIMPOSTO, '
      '   :BASEINCLUSO, :DESCONTOITENS, :TIPOIMPRESSAO, :TOTALPGTOS, '
      ':STATUSANTERIOR, '
      '   :REDUCOESBASE, :ACRESCIMOSBASE, :DTMODIFICACAO, :VOLUMES, '
      ':TERMOCONTRATO, '
      
        '   :ALMOXPADRAO, :CFOPNOTA, :SERIENOTA, :UFDESTINO, :BASECALCICM' +
        'S, '
      ':VALORICMS, '
      '   :VALORISS, :VALORIPI, :BASECALCSUBST, :VALORICMSSUBST, '
      ':VALORSEGURO, '
      '   :TIPOFRETE, :TRANSPORTADORA, :PESOBRUTO, :PESOLIQUIDO, '
      ':ALIQICMSVENDA, '
      '   :VALORISENTAS, :TOTALSERVICOS, :DESCESPECIE, :DESCMARCA, '
      ':DESCNUMERO, '
      '   :INDICADOPELOFAV, :POSSUIICMS, :POSSUIIPI, :POSSUIISS, '
      ':CONTABILIZAICMS, '
      
        '   :MODELO, :VALOROUTRASICMS, :VALORISENTASIPI, :VALOROUTRASIPI,' +
        ' '
      ':FONTE, '
      '   :PLACAVEIC, :ATRATAR, :INTRODUCAO, :PRAZOENTREGA, :GARANTIA, '
      ':SEESTOQUE, '
      '   :PROCESSO, :CARTACONVITE, :TOMADAPRECOS, :DATAABERTURA, '
      ':EXPLICACOES, '
      
        '   :LICITACAOICMS, :SUBSTTRIB, :PJUROSNEGOCIADO, :CONDICOESPAGTO' +
        ', '
      ':TOTALPRODUTOS, '
      '   :VALORIPIITENS, :BASECALCICMSITENS, :VALORICMSITENS, '
      ':BASECALCSUBSTITENS, '
      '   :COBRANCA, :CARTEIRA, :MEDICO, :NF_CUPOM, :DEVOLUCAO, '
      ':BAIXAESTOQUEFISCAL, '
      
        '   :HORA, :MENSAGEMITEM, :NUMEROSERIEECF, :NUMEROECF, :CCF, :CRZ' +
        ', '
      ':DETALHEIMPORTACAO)')
    DeleteSQL.Strings = (
      'delete from SAIDAS'
      'where'
      '  EMPRESA = :OLD_EMPRESA and'
      '  SAIDA = :OLD_SAIDA and'
      '  PDV = :OLD_PDV and'
      '  NUMERO = :OLD_NUMERO and'
      '  DATA = :OLD_DATA and'
      '  FAVORECIDO = :OLD_FAVORECIDO and'
      '  OBS = :OLD_OBS and'
      '  TAX = :OLD_TAX and'
      '  PERCENTUALTAX = :OLD_PERCENTUALTAX and'
      '  DESCONTO = :OLD_DESCONTO and'
      '  PLANOPAGAMENTO = :OLD_PLANOPAGAMENTO and'
      '  VENDEDOR = :OLD_VENDEDOR and'
      '  FRETE = :OLD_FRETE and'
      '  TOTAL = :OLD_TOTAL and'
      '  TIPOENTREGA = :OLD_TIPOENTREGA and'
      '  DATAENTREGA = :OLD_DATAENTREGA and'
      '  IMPORTACAO = :OLD_IMPORTACAO and'
      '  SITUACAO = :OLD_SITUACAO and'
      '  TIPOMOVIMENTO = :OLD_TIPOMOVIMENTO and'
      '  PEDIDO_CLIENTE = :OLD_PEDIDO_CLIENTE and'
      '  OUTRASDESPESAS = :OLD_OUTRASDESPESAS and'
      '  JUROS = :OLD_JUROS and'
      '  POSSUITAX = :OLD_POSSUITAX and'
      '  BAIXAESTOQUE = :OLD_BAIXAESTOQUE and'
      '  CALCCOMISSAO = :OLD_CALCCOMISSAO and'
      '  POSSUIENTREGA = :OLD_POSSUIENTREGA and'
      '  CAMPO01 = :OLD_CAMPO01 and'
      '  CAMPO02 = :OLD_CAMPO02 and'
      '  CAMPO03 = :OLD_CAMPO03 and'
      '  CAMPO04 = :OLD_CAMPO04 and'
      '  IMPRESSO = :OLD_IMPRESSO and'
      '  IMPOSTO = :OLD_IMPOSTO and'
      '  IMPOSTO_INCLUSO = :OLD_IMPOSTO_INCLUSO and'
      '  PCOMISSAO = :OLD_PCOMISSAO and'
      '  CAIXA = :OLD_CAIXA and'
      '  LOCALENTREGA = :OLD_LOCALENTREGA and'
      '  TABELAPADRAO = :OLD_TABELAPADRAO and'
      '  TIPOPADRAO = :OLD_TIPOPADRAO and'
      '  DATACANCELAMENTO = :OLD_DATACANCELAMENTO and'
      '  FUNCCANCELAMENTO = :OLD_FUNCCANCELAMENTO and'
      '  MOTIVOCANCELAMENTO = :OLD_MOTIVOCANCELAMENTO and'
      '  PJUROS = :OLD_PJUROS and'
      '  VALORCOMISSAO = :OLD_VALORCOMISSAO and'
      '  TOTALITENS = :OLD_TOTALITENS and'
      '  VALIDADE = :OLD_VALIDADE and'
      '  CONDICOESPGTO = :OLD_CONDICOESPGTO and'
      '  DATAENTREGUE = :OLD_DATAENTREGUE and'
      '  STATUS = :OLD_STATUS and'
      '  TOTALITENS123 = :OLD_TOTALITENS123 and'
      '  BASEIMPOSTO = :OLD_BASEIMPOSTO and'
      '  BASEINCLUSO = :OLD_BASEINCLUSO and'
      '  DESCONTOITENS = :OLD_DESCONTOITENS and'
      '  TIPOIMPRESSAO = :OLD_TIPOIMPRESSAO and'
      '  TOTALPGTOS = :OLD_TOTALPGTOS and'
      '  STATUSANTERIOR = :OLD_STATUSANTERIOR and'
      '  REDUCOESBASE = :OLD_REDUCOESBASE and'
      '  ACRESCIMOSBASE = :OLD_ACRESCIMOSBASE and'
      '  DTMODIFICACAO = :OLD_DTMODIFICACAO and'
      '  VOLUMES = :OLD_VOLUMES and'
      '  TERMOCONTRATO = :OLD_TERMOCONTRATO and'
      '  ALMOXPADRAO = :OLD_ALMOXPADRAO and'
      '  CFOPNOTA = :OLD_CFOPNOTA and'
      '  SERIENOTA = :OLD_SERIENOTA and'
      '  UFDESTINO = :OLD_UFDESTINO and'
      '  BASECALCICMS = :OLD_BASECALCICMS and'
      '  VALORICMS = :OLD_VALORICMS and'
      '  VALORISS = :OLD_VALORISS and'
      '  VALORIPI = :OLD_VALORIPI and'
      '  BASECALCSUBST = :OLD_BASECALCSUBST and'
      '  VALORICMSSUBST = :OLD_VALORICMSSUBST and'
      '  VALORSEGURO = :OLD_VALORSEGURO and'
      '  TIPOFRETE = :OLD_TIPOFRETE and'
      '  TRANSPORTADORA = :OLD_TRANSPORTADORA and'
      '  PESOBRUTO = :OLD_PESOBRUTO and'
      '  PESOLIQUIDO = :OLD_PESOLIQUIDO and'
      '  ALIQICMSVENDA = :OLD_ALIQICMSVENDA and'
      '  VALORISENTAS = :OLD_VALORISENTAS and'
      '  TOTALSERVICOS = :OLD_TOTALSERVICOS and'
      '  DESCESPECIE = :OLD_DESCESPECIE and'
      '  DESCMARCA = :OLD_DESCMARCA and'
      '  DESCNUMERO = :OLD_DESCNUMERO and'
      '  INDICADOPELOFAV = :OLD_INDICADOPELOFAV and'
      '  POSSUIICMS = :OLD_POSSUIICMS and'
      '  POSSUIIPI = :OLD_POSSUIIPI and'
      '  POSSUIISS = :OLD_POSSUIISS and'
      '  CONTABILIZAICMS = :OLD_CONTABILIZAICMS and'
      '  MODELO = :OLD_MODELO and'
      '  VALOROUTRASICMS = :OLD_VALOROUTRASICMS and'
      '  VALORISENTASIPI = :OLD_VALORISENTASIPI and'
      '  VALOROUTRASIPI = :OLD_VALOROUTRASIPI and'
      '  FONTE = :OLD_FONTE and'
      '  PLACAVEIC = :OLD_PLACAVEIC and'
      '  ATRATAR = :OLD_ATRATAR and'
      '  INTRODUCAO = :OLD_INTRODUCAO and'
      '  PRAZOENTREGA = :OLD_PRAZOENTREGA and'
      '  GARANTIA = :OLD_GARANTIA and'
      '  SEESTOQUE = :OLD_SEESTOQUE and'
      '  PROCESSO = :OLD_PROCESSO and'
      '  CARTACONVITE = :OLD_CARTACONVITE and'
      '  TOMADAPRECOS = :OLD_TOMADAPRECOS and'
      '  DATAABERTURA = :OLD_DATAABERTURA and'
      '  EXPLICACOES = :OLD_EXPLICACOES and'
      '  LICITACAOICMS = :OLD_LICITACAOICMS and'
      '  SUBSTTRIB = :OLD_SUBSTTRIB and'
      '  PJUROSNEGOCIADO = :OLD_PJUROSNEGOCIADO and'
      '  CONDICOESPAGTO = :OLD_CONDICOESPAGTO and'
      '  TOTALPRODUTOS = :OLD_TOTALPRODUTOS and'
      '  VALORIPIITENS = :OLD_VALORIPIITENS and'
      '  BASECALCICMSITENS = :OLD_BASECALCICMSITENS and'
      '  VALORICMSITENS = :OLD_VALORICMSITENS and'
      '  BASECALCSUBSTITENS = :OLD_BASECALCSUBSTITENS and'
      '  COBRANCA = :OLD_COBRANCA and'
      '  CARTEIRA = :OLD_CARTEIRA and'
      '  MEDICO = :OLD_MEDICO and'
      '  NF_CUPOM = :OLD_NF_CUPOM and'
      '  DEVOLUCAO = :OLD_DEVOLUCAO and'
      '  BAIXAESTOQUEFISCAL = :OLD_BAIXAESTOQUEFISCAL and'
      '  HORA = :OLD_HORA and'
      '  MENSAGEMITEM = :OLD_MENSAGEMITEM and'
      '  NUMEROSERIEECF = :OLD_NUMEROSERIEECF and'
      '  NUMEROECF = :OLD_NUMEROECF and'
      '  CCF = :OLD_CCF and'
      '  CRZ = :OLD_CRZ and'
      '  DETALHEIMPORTACAO = :OLD_DETALHEIMPORTACAO')
  end
  inherited C_Tabela: TClientDataSet
    inherited C_TabelaTOTAL: TBCDField
      OnChange = C_TabelaTOTALChange
    end
    inherited C_TabelaDESCONTO: TBCDField
      DisplayFormat = ''
    end
    inherited C_TabelaTABELAPADRAO: TIntegerField
      OnChange = C_TabelaTABELAPADRAOChange
    end
    object C_TabelaicNomeTabelaPadrao: TStringField
      FieldKind = fkInternalCalc
      FieldName = 'icNomeTabelaPadrao'
      Size = 30
    end
  end
  inherited Q_Itens: TIBQuery
    SQL.Strings = (
      'Select '#9't.SaidaItem'#9'as IDITEM,'
      #9't.Saida'#9#9'as IDMestre,'
      '       '#9't.Sequencia'#9'as Sequencia,'
      #9't.Descricao          '#9'as Descricao,'
      #9't.Quantidade       '#9'as Quantidade,'
      #9't.QuantidadeVolume       '#9'as QuantidadeVolume,'
      #9't.Preco'#9#9'as Preco,'
      #9't.Item'#9#9'as Item,'
      #9't.USOTIPOITEM'#9'as UsoTipoItem,'
      #9't.SubTotalItem'#9'as SubTotalItem,'
      #9't.SubTotalItem'#9'as SubTotal,'
      #9't.Ordem'#9#9'as Ordem,'
      #9't.TabelaPreco'#9'as TabelaPreco,'
      #9't.PrecoTabela'#9'as PrecoTabela,'
      #9't.RateioDesconto'#9'as RateioDesconto,'
      #9't.HasChildren'#9'as HasChildren,'
      #9't.CustoMedio'#9'as CustoMedio,'
      '                t.ContaVenda          as ContaVenda,'
      '                t.Taxavel                 as Taxavel,'
      #9't.Producao'#9'as Producao,'
      #9't.FuncProducao'#9'as FuncProducao,'
      #9't.Coluna1'#9#9'as Coluna1,'
      #9't.Coluna2'#9#9'as Coluna2,'
      #9't.Coluna3'#9#9'as Coluna3,'
      #9't.Coluna4'#9#9'as Coluna4,'
      #9't.MaxDesconto'#9'as MaxDesconto,'
      #9't.Quantidade'#9'as OldQuantidade,'
      #9't.EntradaItem'#9'as EntradaItem,'
      #9't.Despesa'#9'as Despesa,'
      #9't.CustoContabil'#9'as CustoContabil,'
      #9't.Mesclado'#9'as Mesclado,'
      #9't.ITEM'#9#9'as OLDITEM,'
      #9't.QtdFaturada'#9'as QtdFaturada,'
      #9't.QtdMontagem     '#9'as QtdMontagem,'
      #9't.Status'#9#9'as Status,'
      #9't.Status'#9#9'as StatusOld,'
      #9't.Unidade '#9'as Unidade,'
      #9't.Fator'#9'                as Fator,'
      '                t.numerolote             as NumeroLote,'
      #9't.N_UsoTipoItem'#9'as N_UsoTipoItem,'
      #9't.Preco'#9#9'as OldPreco,'
      #9't.Unidade'#9#9'as OldUnidade,'
      #9't.Desconto'#9'as Desconto,'
      #9't.Promocao'#9'as Promocao,'
      #9't.PrecoSemPromocao as PrecoSemPromocao,'
      '                t.BaixaEstoqueFiscal as BaixaEstoqueFiscal,'
      #9't.BaixaEstoque'#9'as BaixaEstoque,'
      #9't.Almoxarifado'#9'as Almoxarifado,'
      #9't.DescricaoComplementar as DescricaoComplementar,'
      '                t.OrdemMontagem   as OrdemMontagem,'
      '                t.BASECALCICMSPROD ,'
      '                t.IPI ,'
      '                t.ALIQICMS ,'
      '                t.CST ,'
      '                t.REDUCAOCST ,'
      '                t.SITUACAOECF ,'
      '                t.CFOPNOTA , '
      '                t.DESCONTO ,'
      '                t.BASECALCSUBSTPROD ,'
      '                t.VALORIPIPROD , '
      '                t.TVA ,'
      '                t.NUMEROITEM,'
      '                t.REGISTRO,'
      '                t.VALORICMSPROD,'
      '                t.VALORICMSSUBSTPROD,'
      '                t.VALORISENTASPROD,'
      '                t.DATACONTATO,'
      '                t.CFOPCST, '
      '                t.IDTRIBFEDERAL,'
      '                t.VALORPISPROD,'
      '                t.VALORCOFINSPROD, '
      ''
      ''
      '                t.ALIQIPI,'
      '                t.ALIQPIS,'
      '                t.ALIQCOFINS,'
      '                t.CSTIPI,'
      '                t.CSTPISCOFINS,'
      '                T.PDESCONTO,           '
      '                T.PDV,'
      '                T.IMPORTACAO,'
      '                T.PCOMISSAO,'
      '                I.IDTRIBFEDERAL  as I_IDTRIBFEDERAL,'
      #9'i.TIPOITEM          '#9'as  I_TIPOITEM,'
      #9'i.CODIGO            '#9'as  I_CODIGO,'
      #9'i.CODIGOBARRAS  as  I_CODIGOBARRAS,'
      #9'i.DESCRICAOCOMPRA   as  I_DESCRICAOCOMPRA,'
      #9'i.GRUPO             '#9'as  I_GRUPO,'
      #9'i.DESCRICAO         '#9'as  I_DESCRICAO,'
      #9'i.REFERENCIA'#9'as  I_REFERENCIA,'
      #9'i.TAXAVEL           '#9'as  I_TAXAVEL,'
      #9'i.CUSTOMEDIO      as  I_CUSTOMEDIO,'
      #9'i.ULTIMOFORNECEDOR  as  I_ULTIMOFORNECEDOR,'
      #9'i.QTDEMINIMO       as  I_QTDEMINIMO,'
      #9'i.QTDEMAXIMO   '#9'as  I_QTDEMAXIMO,'
      #9'i.PONTOPEDIDO  '#9'as  I_PONTOPEDIDO,'
      #9'i.PERCENTUAL      as  I_PERCENTUAL,'
      #9'i.APLICARANTESTAX   as  I_APLICARANTESTAX,'
      #9'i.LOCALIZACAO      as  I_LOCALIZACAO,'
      #9'i.ESTOQUE'#9'as  I_ESTOQUE,'
      #9'i.ESTOQUEVOLUME'#9'as  I_ESTOQUEVOLUME,'
      #9'i.COMISSAO          '#9'as  I_COMISSAO,'
      #9'i.DESCONTOMAXIMO    as  I_DESCONTOMAXIMO,'
      #9'i.TAXINCLUSO        as  I_TAXINCLUSO,'
      #9'i.CONTA_VENDA    as  I_CONTA_VENDA,'
      #9'i.CONTA_CUSTO    as  I_CONTA_CUSTO,'
      #9'i.CONTA_INVENT   as  I_CONTA_INVENT,'
      #9'i.BALANCO'#9'as  I_BALANCO,'
      #9'i.FOTO'#9#9'as  I_FOTO, '
      #9'i.PROMOCAO'#9'as  I_PROMOCAO,'
      '                i.FATORLUCRO      as  I_FATORLUCRO,'
      '                i.SEMLUCRO  '#9'as  I_SEMLUCRO,'
      #9'i.UNIDADE           '#9'as  I_UNIDADE,'
      #9'i.UnidadeEntrada'#9'as  I_UnidadeEntrada,'
      #9'i.UnidadeCarga'#9'as  I_UnidadeCarga,'
      #9'i.UnidadeVarejo'#9'as  I_UnidadeVarejo,'
      #9'i.UnidadeMinima      as  I_UnidadeMinima,'
      #9'i.FatorUndVenda'#9'as  I_FatorUndVenda,'
      #9'i.FatorUndCompra'#9'as  I_FatorUndCompra,'
      '                i.ComLucro'#9'as  I_ComLucro,'
      '                i.PesoBruto               as I_PesoBruto,'
      '                i.PesoLiquido            as I_PesoLiquido,'
      #9'i.DescricaoComplementar as I_DescricaoComplementar,'
      #9'i.DescricaoTecnica'#9'as  I_DescricaoTecnica,'
      '                i.GrupoComissao as      I_GRUPOCOMISSAO,'
      '                i.INDEXADOR as I_INDEXADOR,'
      '                I.clasfiscal as I_CLASFISCAL,'
      #9'u.Descricao'#9'as  DescricaoUnidade,'
      #9'u.Inteira'#9#9'as  UnidadeInteira,'
      #9'pdf.Producao'#9'as  ChaveProducaoFunc,'
      #9'g.DescontoMaximo'#9'as  DescontoMaximoGrupo,'
      #9'g.Foto'#9#9'as  FotoGrupo,'
      #9'g.DescricaoGrupo'#9'as  DescricaoGrupo,'
      #9'fb.Descricao'#9'as  DescFabricante,'
      '                t.EMPRESA,'
      '                T.SITUACAO           AS SITUACAO,'
      '                t.valorpisprod,'
      '                t.valorcofinsprod,'
      #9't.RATEIODESPESAS,'
      '                t.RATEIOFRETE,'
      '               T.RATEIOSEGURO '
      'from'#9'((((SAIDASITENS t  LEFT JOIN  ITENS I on I.ITEM = t.ITEM)'
      #9'left join UNIDADES u on I.Unidade = u.Unidade)'
      #9'left join GRUPOS g on g.Grupo = i.Grupo)'
      #9'left join FABRICANTES fb ON fb.Fabricante = i.Fabricante)'
      #9'left join PRODUCOESFUNC pdf on pdf.SAIDAITEM = t.SAIDAITEM'
      'where t.SAIDA = :IDMESTRE')
  end
  inherited U_Itens: TIBUpdateSQL
    RefreshSQL.Strings = (
      'Select '
      '  EMPRESA,'
      '  SAIDA,'
      '  SAIDAITEM,'
      '  PDV,'
      '  SEQUENCIA,'
      '  ITEM,'
      '  DESCRICAO,'
      '  QUANTIDADE,'
      '  PRECO,'
      '  TAXAVEL,'
      '  IMPORTACAO,'
      '  CONTAVENDA,'
      '  TABELAPRECO,'
      '  PRECOTABELA,'
      '  USOTIPOITEM,'
      '  SUBTOTALITEM,'
      '  ORDEM,'
      '  CUSTOMEDIO,'
      '  CUSTOCONTABIL,'
      '  RATEIODESCONTO,'
      '  HASCHILDREN,'
      '  PRODUCAO,'
      '  FUNCPRODUCAO,'
      '  COLUNA1,'
      '  COLUNA2,'
      '  COLUNA3,'
      '  COLUNA4,'
      '  MAXDESCONTO,'
      '  DESPESA,'
      '  ENTRADAITEM,'
      '  CONTRATOREF,'
      '  QTDFATURADA,'
      '  MESCLADO,'
      '  STATUS,'
      '  QTDMONTAGEM,'
      '  NUMEROLOTE,'
      '  UNIDADE,'
      '  FATOR,'
      '  N_USOTIPOITEM,'
      '  DESCONTO,'
      '  DESCRICAOCOMPLEMENTAR,'
      '  PROMOCAO,'
      '  PRECOSEMPROMOCAO,'
      '  BAIXAESTOQUE,'
      '  ALMOXARIFADO,'
      '  ORDEMMONTAGEM,'
      '  BASECALCICMSPROD,'
      '  IPI,'
      '  ALIQICMS,'
      '  CST,'
      '  REDUCAOCST,'
      '  SITUACAOECF,'
      '  CFOPNOTA,'
      '  BASECALCSUBSTPROD,'
      '  VALORIPIPROD,'
      '  TVA,'
      '  NUMEROITEM,'
      '  REGISTRO,'
      '  VALORICMSPROD,'
      '  VALORISENTASPROD,'
      '  VALORICMSSUBSTPROD,'
      '  PDESCONTO,'
      '  QTDDEVOLVIDO,'
      '  QTDACERTADO,'
      '  DATACONTATO,'
      '  CFOPCST,'
      '  IDCFOPCST,'
      '  BAIXAESTOQUEFISCAL,'
      '  IDTRIBFEDERAL,'
      '  QUANTIDADEVOLUME,'
      '  CSTPISCOFINS,'
      '  ALIQPIS,'
      '  ALIQCOFINS,'
      '  CSTIPI,'
      '  ALIQIPI,'
      '  VALORPISPROD,'
      '  VALORCOFINSPROD,'
      '  ULTIMOPRECOCOMPRA,'
      '  V_BCII,'
      '  V_DESPADUII,'
      '  V_II,'
      '  V_IOFII,'
      '  PCOMISSAO'
      'from SAIDASITENS '
      'where'
      '  EMPRESA = :EMPRESA and'
      '  SAIDA = :SAIDA and'
      '  SAIDAITEM = :SAIDAITEM and'
      '  PDV = :PDV and'
      '  SEQUENCIA = :SEQUENCIA and'
      '  ITEM = :ITEM and'
      '  DESCRICAO = :DESCRICAO and'
      '  QUANTIDADE = :QUANTIDADE and'
      '  PRECO = :PRECO and'
      '  TAXAVEL = :TAXAVEL and'
      '  IMPORTACAO = :IMPORTACAO and'
      '  CONTAVENDA = :CONTAVENDA and'
      '  TABELAPRECO = :TABELAPRECO and'
      '  PRECOTABELA = :PRECOTABELA and'
      '  USOTIPOITEM = :USOTIPOITEM and'
      '  SUBTOTALITEM = :SUBTOTALITEM and'
      '  ORDEM = :ORDEM and'
      '  CUSTOMEDIO = :CUSTOMEDIO and'
      '  CUSTOCONTABIL = :CUSTOCONTABIL and'
      '  RATEIODESCONTO = :RATEIODESCONTO and'
      '  HASCHILDREN = :HASCHILDREN and'
      '  PRODUCAO = :PRODUCAO and'
      '  FUNCPRODUCAO = :FUNCPRODUCAO and'
      '  COLUNA1 = :COLUNA1 and'
      '  COLUNA2 = :COLUNA2 and'
      '  COLUNA3 = :COLUNA3 and'
      '  COLUNA4 = :COLUNA4 and'
      '  MAXDESCONTO = :MAXDESCONTO and'
      '  DESPESA = :DESPESA and'
      '  ENTRADAITEM = :ENTRADAITEM and'
      '  CONTRATOREF = :CONTRATOREF and'
      '  QTDFATURADA = :QTDFATURADA and'
      '  MESCLADO = :MESCLADO and'
      '  STATUS = :STATUS and'
      '  QTDMONTAGEM = :QTDMONTAGEM and'
      '  NUMEROLOTE = :NUMEROLOTE and'
      '  UNIDADE = :UNIDADE and'
      '  FATOR = :FATOR and'
      '  N_USOTIPOITEM = :N_USOTIPOITEM and'
      '  DESCONTO = :DESCONTO and'
      '  DESCRICAOCOMPLEMENTAR = :DESCRICAOCOMPLEMENTAR and'
      '  PROMOCAO = :PROMOCAO and'
      '  PRECOSEMPROMOCAO = :PRECOSEMPROMOCAO and'
      '  BAIXAESTOQUE = :BAIXAESTOQUE and'
      '  ALMOXARIFADO = :ALMOXARIFADO and'
      '  ORDEMMONTAGEM = :ORDEMMONTAGEM and'
      '  BASECALCICMSPROD = :BASECALCICMSPROD and'
      '  IPI = :IPI and'
      '  ALIQICMS = :ALIQICMS and'
      '  CST = :CST and'
      '  REDUCAOCST = :REDUCAOCST and'
      '  SITUACAOECF = :SITUACAOECF and'
      '  CFOPNOTA = :CFOPNOTA and'
      '  BASECALCSUBSTPROD = :BASECALCSUBSTPROD and'
      '  VALORIPIPROD = :VALORIPIPROD and'
      '  TVA = :TVA and'
      '  NUMEROITEM = :NUMEROITEM and'
      '  REGISTRO = :REGISTRO and'
      '  VALORICMSPROD = :VALORICMSPROD and'
      '  VALORISENTASPROD = :VALORISENTASPROD and'
      '  VALORICMSSUBSTPROD = :VALORICMSSUBSTPROD and'
      '  PDESCONTO = :PDESCONTO and'
      '  QTDDEVOLVIDO = :QTDDEVOLVIDO and'
      '  QTDACERTADO = :QTDACERTADO and'
      '  DATACONTATO = :DATACONTATO and'
      '  CFOPCST = :CFOPCST and'
      '  IDCFOPCST = :IDCFOPCST and'
      '  BAIXAESTOQUEFISCAL = :BAIXAESTOQUEFISCAL and'
      '  IDTRIBFEDERAL = :IDTRIBFEDERAL and'
      '  QUANTIDADEVOLUME = :QUANTIDADEVOLUME and'
      '  CSTPISCOFINS = :CSTPISCOFINS and'
      '  ALIQPIS = :ALIQPIS and'
      '  ALIQCOFINS = :ALIQCOFINS and'
      '  CSTIPI = :CSTIPI and'
      '  ALIQIPI = :ALIQIPI and'
      '  VALORPISPROD = :VALORPISPROD and'
      '  VALORCOFINSPROD = :VALORCOFINSPROD and'
      '  ULTIMOPRECOCOMPRA = :ULTIMOPRECOCOMPRA and'
      '  V_BCII = :V_BCII and'
      '  V_DESPADUII = :V_DESPADUII and'
      '  V_II = :V_II and'
      '  V_IOFII = :V_IOFII and'
      '  PCOMISSAO = :PCOMISSAO')
    ModifySQL.Strings = (
      'update SAIDASITENS'
      'set'
      '  EMPRESA = :EMPRESA,'
      '  SAIDA = :SAIDA,'
      '  SAIDAITEM = :SAIDAITEM,'
      '  PDV = :PDV,'
      '  SEQUENCIA = :SEQUENCIA,'
      '  ITEM = :ITEM,'
      '  DESCRICAO = :DESCRICAO,'
      '  QUANTIDADE = :QUANTIDADE,'
      '  PRECO = :PRECO,'
      '  TAXAVEL = :TAXAVEL,'
      '  IMPORTACAO = :IMPORTACAO,'
      '  CONTAVENDA = :CONTAVENDA,'
      '  TABELAPRECO = :TABELAPRECO,'
      '  PRECOTABELA = :PRECOTABELA,'
      '  USOTIPOITEM = :USOTIPOITEM,'
      '  SUBTOTALITEM = :SUBTOTALITEM,'
      '  ORDEM = :ORDEM,'
      '  CUSTOMEDIO = :CUSTOMEDIO,'
      '  CUSTOCONTABIL = :CUSTOCONTABIL,'
      '  RATEIODESCONTO = :RATEIODESCONTO,'
      '  HASCHILDREN = :HASCHILDREN,'
      '  PRODUCAO = :PRODUCAO,'
      '  FUNCPRODUCAO = :FUNCPRODUCAO,'
      '  COLUNA1 = :COLUNA1,'
      '  COLUNA2 = :COLUNA2,'
      '  COLUNA3 = :COLUNA3,'
      '  COLUNA4 = :COLUNA4,'
      '  MAXDESCONTO = :MAXDESCONTO,'
      '  DESPESA = :DESPESA,'
      '  ENTRADAITEM = :ENTRADAITEM,'
      '  CONTRATOREF = :CONTRATOREF,'
      '  QTDFATURADA = :QTDFATURADA,'
      '  MESCLADO = :MESCLADO,'
      '  STATUS = :STATUS,'
      '  QTDMONTAGEM = :QTDMONTAGEM,'
      '  NUMEROLOTE = :NUMEROLOTE,'
      '  UNIDADE = :UNIDADE,'
      '  FATOR = :FATOR,'
      '  N_USOTIPOITEM = :N_USOTIPOITEM,'
      '  DESCONTO = :DESCONTO,'
      '  DESCRICAOCOMPLEMENTAR = :DESCRICAOCOMPLEMENTAR,'
      '  PROMOCAO = :PROMOCAO,'
      '  PRECOSEMPROMOCAO = :PRECOSEMPROMOCAO,'
      '  BAIXAESTOQUE = :BAIXAESTOQUE,'
      '  ALMOXARIFADO = :ALMOXARIFADO,'
      '  ORDEMMONTAGEM = :ORDEMMONTAGEM,'
      '  BASECALCICMSPROD = :BASECALCICMSPROD,'
      '  IPI = :IPI,'
      '  ALIQICMS = :ALIQICMS,'
      '  CST = :CST,'
      '  REDUCAOCST = :REDUCAOCST,'
      '  SITUACAOECF = :SITUACAOECF,'
      '  CFOPNOTA = :CFOPNOTA,'
      '  BASECALCSUBSTPROD = :BASECALCSUBSTPROD,'
      '  VALORIPIPROD = :VALORIPIPROD,'
      '  TVA = :TVA,'
      '  NUMEROITEM = :NUMEROITEM,'
      '  REGISTRO = :REGISTRO,'
      '  VALORICMSPROD = :VALORICMSPROD,'
      '  VALORISENTASPROD = :VALORISENTASPROD,'
      '  VALORICMSSUBSTPROD = :VALORICMSSUBSTPROD,'
      '  PDESCONTO = :PDESCONTO,'
      '  QTDDEVOLVIDO = :QTDDEVOLVIDO,'
      '  QTDACERTADO = :QTDACERTADO,'
      '  DATACONTATO = :DATACONTATO,'
      '  CFOPCST = :CFOPCST,'
      '  IDCFOPCST = :IDCFOPCST,'
      '  BAIXAESTOQUEFISCAL = :BAIXAESTOQUEFISCAL,'
      '  IDTRIBFEDERAL = :IDTRIBFEDERAL,'
      '  QUANTIDADEVOLUME = :QUANTIDADEVOLUME,'
      '  CSTPISCOFINS = :CSTPISCOFINS,'
      '  ALIQPIS = :ALIQPIS,'
      '  ALIQCOFINS = :ALIQCOFINS,'
      '  CSTIPI = :CSTIPI,'
      '  ALIQIPI = :ALIQIPI,'
      '  VALORPISPROD = :VALORPISPROD,'
      '  VALORCOFINSPROD = :VALORCOFINSPROD,'
      '  ULTIMOPRECOCOMPRA = :ULTIMOPRECOCOMPRA,'
      '  V_BCII = :V_BCII,'
      '  V_DESPADUII = :V_DESPADUII,'
      '  V_II = :V_II,'
      '  V_IOFII = :V_IOFII,'
      '  PCOMISSAO = :PCOMISSAO,'
      '  SITUACAO  = :SITUACAO,'
      '  VALORPISPROD = :VALORPISPROD, '
      '  VALORCOFINSPROD = :VALORCOFINSPROD,'
      '  RATEIODESPESAS = :RATEIODESPESAS,'
      '  RATEIOFRETE = :RATEIOFRETE ,'
      '  RATEIOSEGURO = :RATEIOSEGURO'
      'where'
      '  SAIDA = :OLD_SAIDA')
    InsertSQL.Strings = (
      'insert into SAIDASITENS'
      '  (EMPRESA, SAIDA, SAIDAITEM, PDV, SEQUENCIA, ITEM, DESCRICAO, '
      'QUANTIDADE, '
      '   PRECO, TAXAVEL, IMPORTACAO, CONTAVENDA, TABELAPRECO, '
      'PRECOTABELA, USOTIPOITEM, '
      '   SUBTOTALITEM, ORDEM, CUSTOMEDIO, CUSTOCONTABIL, '
      'RATEIODESCONTO, HASCHILDREN, '
      '   PRODUCAO, FUNCPRODUCAO, COLUNA1, COLUNA2, COLUNA3, COLUNA4, '
      'MAXDESCONTO, '
      '   DESPESA, ENTRADAITEM, CONTRATOREF, QTDFATURADA, MESCLADO, '
      'STATUS, QTDMONTAGEM, '
      '   NUMEROLOTE, UNIDADE, FATOR, N_USOTIPOITEM, DESCONTO, '
      'DESCRICAOCOMPLEMENTAR, '
      '   PROMOCAO, PRECOSEMPROMOCAO, BAIXAESTOQUE, ALMOXARIFADO, '
      'ORDEMMONTAGEM, '
      
        '   BASECALCICMSPROD, IPI, ALIQICMS, CST, REDUCAOCST, SITUACAOECF' +
        ', '
      'CFOPNOTA, '
      '   BASECALCSUBSTPROD, VALORIPIPROD, TVA, NUMEROITEM, REGISTRO, '
      'VALORICMSPROD, '
      '   VALORISENTASPROD, VALORICMSSUBSTPROD, PDESCONTO, '
      'QTDDEVOLVIDO, QTDACERTADO, '
      '   DATACONTATO, CFOPCST, IDCFOPCST, BAIXAESTOQUEFISCAL, '
      'IDTRIBFEDERAL, '
      
        '   QUANTIDADEVOLUME, CSTPISCOFINS, ALIQPIS, ALIQCOFINS, CSTIPI, ' +
        'ALIQIPI, '
      '   VALORPISPROD, VALORCOFINSPROD, ULTIMOPRECOCOMPRA, V_BCII, '
      'V_DESPADUII, '
      '   V_II, V_IOFII, PCOMISSAO,SITUACAO,VALORPISPROD,'
      '  VALORCOFINSPROD,RATEIODESPESAS,RATEIOFRETE,RATEIOSEGURO )'
      'values'
      
        '  (:EMPRESA, :IDMESTRE, :IDITEM, :PDV, :SEQUENCIA, :ITEM, :DESCR' +
        'ICAO, '
      ':QUANTIDADE, '
      '   :PRECO, :TAXAVEL, :IMPORTACAO, :CONTAVENDA, :TABELAPRECO, '
      ':PRECOTABELA, '
      
        '   :USOTIPOITEM, :SUBTOTALITEM, :ORDEM, :CUSTOMEDIO, :CUSTOCONTA' +
        'BIL, '
      ':RATEIODESCONTO, '
      '   :HASCHILDREN, :PRODUCAO, :FUNCPRODUCAO, :COLUNA1, :COLUNA2, '
      ':COLUNA3, '
      
        '   :COLUNA4, :MAXDESCONTO, :DESPESA, :ENTRADAITEM, :CONTRATOREF,' +
        ' '
      ':QTDFATURADA, '
      
        '   :MESCLADO, :STATUS, :QTDMONTAGEM, :NUMEROLOTE, :UNIDADE, :FAT' +
        'OR, '
      ':N_USOTIPOITEM, '
      '   :DESCONTO, :DESCRICAOCOMPLEMENTAR, :PROMOCAO, '
      ':PRECOSEMPROMOCAO, :BAIXAESTOQUE, '
      '   :ALMOXARIFADO, :ORDEMMONTAGEM, :BASECALCICMSPROD, :IPI, '
      ':ALIQICMS, :CST, '
      '   :REDUCAOCST, :SITUACAOECF, :CFOPNOTA, :BASECALCSUBSTPROD, '
      ':VALORIPIPROD, '
      
        '   :TVA, :NUMEROITEM, :REGISTRO, :VALORICMSPROD, :VALORISENTASPR' +
        'OD, '
      ':VALORICMSSUBSTPROD, '
      '   :PDESCONTO, :QTDDEVOLVIDO, :QTDACERTADO, :DATACONTATO, '
      ':CFOPCST, :IDCFOPCST, '
      '   :BAIXAESTOQUEFISCAL, :IDTRIBFEDERAL, :QUANTIDADEVOLUME, '
      ':CSTPISCOFINS, '
      '   :ALIQPIS, :ALIQCOFINS, :CSTIPI, :ALIQIPI, :VALORPISPROD, '
      ':VALORCOFINSPROD, '
      '   :ULTIMOPRECOCOMPRA, :V_BCII, :V_DESPADUII, :V_II, :V_IOFII, '
      ':PCOMISSAO,:SITUACAO,:VALORPISPROD,'
      '  :VALORCOFINSPROD,:RATEIODESPESAS,:RATEIOFRETE,:RATEIOSEGURO )')
    DeleteSQL.Strings = (
      'delete from SAIDASITENS'
      'where'
      '  EMPRESA = :OLD_EMPRESA and'
      '  SAIDA = :OLD_SAIDA and'
      '  SAIDAITEM = :OLD_SAIDAITEM and'
      '  PDV = :OLD_PDV and'
      '  SEQUENCIA = :OLD_SEQUENCIA and'
      '  ITEM = :OLD_ITEM and'
      '  DESCRICAO = :OLD_DESCRICAO and'
      '  QUANTIDADE = :OLD_QUANTIDADE and'
      '  PRECO = :OLD_PRECO and'
      '  TAXAVEL = :OLD_TAXAVEL and'
      '  IMPORTACAO = :OLD_IMPORTACAO and'
      '  CONTAVENDA = :OLD_CONTAVENDA and'
      '  TABELAPRECO = :OLD_TABELAPRECO and'
      '  PRECOTABELA = :OLD_PRECOTABELA and'
      '  USOTIPOITEM = :OLD_USOTIPOITEM and'
      '  SUBTOTALITEM = :OLD_SUBTOTALITEM and'
      '  ORDEM = :OLD_ORDEM and'
      '  CUSTOMEDIO = :OLD_CUSTOMEDIO and'
      '  CUSTOCONTABIL = :OLD_CUSTOCONTABIL and'
      '  RATEIODESCONTO = :OLD_RATEIODESCONTO and'
      '  HASCHILDREN = :OLD_HASCHILDREN and'
      '  PRODUCAO = :OLD_PRODUCAO and'
      '  FUNCPRODUCAO = :OLD_FUNCPRODUCAO and'
      '  COLUNA1 = :OLD_COLUNA1 and'
      '  COLUNA2 = :OLD_COLUNA2 and'
      '  COLUNA3 = :OLD_COLUNA3 and'
      '  COLUNA4 = :OLD_COLUNA4 and'
      '  MAXDESCONTO = :OLD_MAXDESCONTO and'
      '  DESPESA = :OLD_DESPESA and'
      '  ENTRADAITEM = :OLD_ENTRADAITEM and'
      '  CONTRATOREF = :OLD_CONTRATOREF and'
      '  QTDFATURADA = :OLD_QTDFATURADA and'
      '  MESCLADO = :OLD_MESCLADO and'
      '  STATUS = :OLD_STATUS and'
      '  QTDMONTAGEM = :OLD_QTDMONTAGEM and'
      '  NUMEROLOTE = :OLD_NUMEROLOTE and'
      '  UNIDADE = :OLD_UNIDADE and'
      '  FATOR = :OLD_FATOR and'
      '  N_USOTIPOITEM = :OLD_N_USOTIPOITEM and'
      '  DESCONTO = :OLD_DESCONTO and'
      '  DESCRICAOCOMPLEMENTAR = :OLD_DESCRICAOCOMPLEMENTAR and'
      '  PROMOCAO = :OLD_PROMOCAO and'
      '  PRECOSEMPROMOCAO = :OLD_PRECOSEMPROMOCAO and'
      '  BAIXAESTOQUE = :OLD_BAIXAESTOQUE and'
      '  ALMOXARIFADO = :OLD_ALMOXARIFADO and'
      '  ORDEMMONTAGEM = :OLD_ORDEMMONTAGEM and'
      '  BASECALCICMSPROD = :OLD_BASECALCICMSPROD and'
      '  IPI = :OLD_IPI and'
      '  ALIQICMS = :OLD_ALIQICMS and'
      '  CST = :OLD_CST and'
      '  REDUCAOCST = :OLD_REDUCAOCST and'
      '  SITUACAOECF = :OLD_SITUACAOECF and'
      '  CFOPNOTA = :OLD_CFOPNOTA and'
      '  BASECALCSUBSTPROD = :OLD_BASECALCSUBSTPROD and'
      '  VALORIPIPROD = :OLD_VALORIPIPROD and'
      '  TVA = :OLD_TVA and'
      '  NUMEROITEM = :OLD_NUMEROITEM and'
      '  REGISTRO = :OLD_REGISTRO and'
      '  VALORICMSPROD = :OLD_VALORICMSPROD and'
      '  VALORISENTASPROD = :OLD_VALORISENTASPROD and'
      '  VALORICMSSUBSTPROD = :OLD_VALORICMSSUBSTPROD and'
      '  PDESCONTO = :OLD_PDESCONTO and'
      '  QTDDEVOLVIDO = :OLD_QTDDEVOLVIDO and'
      '  QTDACERTADO = :OLD_QTDACERTADO and'
      '  DATACONTATO = :OLD_DATACONTATO and'
      '  CFOPCST = :OLD_CFOPCST and'
      '  IDCFOPCST = :OLD_IDCFOPCST and'
      '  BAIXAESTOQUEFISCAL = :OLD_BAIXAESTOQUEFISCAL and'
      '  IDTRIBFEDERAL = :OLD_IDTRIBFEDERAL and'
      '  QUANTIDADEVOLUME = :OLD_QUANTIDADEVOLUME and'
      '  CSTPISCOFINS = :OLD_CSTPISCOFINS and'
      '  ALIQPIS = :OLD_ALIQPIS and'
      '  ALIQCOFINS = :OLD_ALIQCOFINS and'
      '  CSTIPI = :OLD_CSTIPI and'
      '  ALIQIPI = :OLD_ALIQIPI and'
      '  VALORPISPROD = :OLD_VALORPISPROD and'
      '  VALORCOFINSPROD = :OLD_VALORCOFINSPROD and'
      '  ULTIMOPRECOCOMPRA = :OLD_ULTIMOPRECOCOMPRA and'
      '  V_BCII = :OLD_V_BCII and'
      '  V_DESPADUII = :OLD_V_DESPADUII and'
      '  V_II = :OLD_V_II and'
      '  V_IOFII = :OLD_V_IOFII and'
      '  PCOMISSAO = :OLD_PCOMISSAO')
  end
  inherited C_Itens: TClientDataSet
    Top = 101
    object C_ItensicIG: TStringField
      FieldKind = fkInternalCalc
      FieldName = 'icIG'
      Size = 1
    end
    object C_ItensicX: TStringField
      FieldKind = fkInternalCalc
      FieldName = 'icX'
      Size = 1
    end
    object C_ItensDescricaoGrupo: TStringField
      FieldName = 'DescricaoGrupo'
      Origin = 'GRUPOS.DESCRICAOGRUPO'
      Size = 50
    end
    object C_ItensDescFabricante: TStringField
      FieldName = 'DescFabricante'
      Origin = 'FABRICANTES.DESCFABRICANTE'
      Size = 50
    end
    object C_ItensicCusto: TStringField
      FieldKind = fkInternalCalc
      FieldName = 'icCusto'
      Size = 15
    end
    object C_ItensicMPV: TStringField
      FieldKind = fkInternalCalc
      FieldName = 'icMPV'
      Size = 15
    end
    object C_ItensicEstoque: TBCDField
      FieldKind = fkInternalCalc
      FieldName = 'icEstoque'
      Size = 3
    end
  end
  inherited Q_TiposMovimento: TIBQuery
    SQL.Strings = (
      'Select  t.*, tp.Descricao as DescTipoPadrao, tp.TipoOrigem '
      'From TiposMovimento t, TiposPadrao tp'
      
        'Where t.TipoPadrao = tp.TipoPadrao and t.Tipo = '#39'S'#39'  and t.TipoP' +
        'adrao in (1,2,3,4,5,6) and (t.Serie <> '#39'ECF'#39' or t.Serie is null)'
      'Order by t.ordem, t.TipoPadrao, t.TipoMovimento')
  end
  inherited Q_PlanosPagamento: TIBQuery
    Left = 899
    Top = 363
  end
  inherited P_PlanosPagamento: TDataSetProvider
    Left = 879
    Top = 431
  end
  inherited C_PlanosPagamento: TClientDataSet
    Left = 853
    Top = 528
    object C_PlanosPagamentoicResumo: TStringField
      FieldKind = fkInternalCalc
      FieldName = 'icResumo'
      Size = 200
    end
  end
  inherited C_ProdutosPreco: TClientDataSet
    inherited C_ProdutosPrecoPRODUTOPRECO: TIntegerField
      Origin = 'PRODUTOSPRECO.PRODUTOPRECO'
    end
    inherited C_ProdutosPrecoBASEADA: TStringField
      Origin = 'TABELASPRECO.BASEADA'
    end
    inherited C_ProdutosPrecoPERCENTUAL: TBCDField
      Origin = 'TABELASPRECO.PERCENTUAL'
    end
    inherited C_ProdutosPrecoPRECOPROMOCAO: TBCDField
      Origin = 'PRODUTOSPRECO.PRECOPROMOCAO'
    end
    inherited C_ProdutosPrecoPRECO_NORMAL: TBCDField
      Origin = 'PRODUTOSPRECO.PRECO_NORMAL'
    end
  end
  inherited Q_Parcelas: TIBQuery
    Left = 445
    Top = 6
  end
  inherited C_Parcelas: TClientDataSet
    OnCalcFields = C_ParcelasCalcFields
    object C_Parcelas_icSelecionado: TIntegerField [0]
      FieldKind = fkInternalCalc
      FieldName = '_icSelecionado'
    end
    object C_ParcelasValorAReceber: TCurrencyField
      FieldKind = fkInternalCalc
      FieldName = 'ValorAReceber'
    end
    object C_ParcelasPagamento: TCurrencyField
      FieldKind = fkInternalCalc
      FieldName = 'Pagamento'
    end
    object C_ParcelasJuros: TCurrencyField
      FieldKind = fkInternalCalc
      FieldName = 'Juros'
    end
    object C_ParcelasVENDA: TIntegerField
      FieldName = 'VENDA'
      Origin = 'TITULOSARECEBER.VENDA'
    end
  end
  inherited Q_Funcs: TIBQuery
    Top = 195
  end
  inherited C_LocaisEntrega: TClientDataSet
    inherited C_LocaisEntregaENTREGA: TIntegerField
      Origin = 'FAVORECIDOSENTREGA.ENTREGA'
    end
    inherited C_LocaisEntregaFAVORECIDO: TIntegerField
      Origin = 'FAVORECIDOSENTREGA.FAVORECIDO'
    end
    inherited C_LocaisEntregaDESCRICAO: TStringField
      Origin = 'FAVORECIDOSENTREGA.DESCRICAO'
    end
  end
  inherited C_MesclagensDS: TDataSource
    Left = 155
    Top = 484
  end
  inherited Q_Status: TIBQuery
    Left = 228
  end
  inherited C_MensagensOperacoes: TClientDataSet
    inherited C_MensagensOperacoesMENSAGEMOPERACAO: TIntegerField
      Origin = 'MENSAGENSOPERACOES.MENSAGEMOPERACAO'
    end
    inherited C_MensagensOperacoesDESCRICAO: TStringField
      Origin = 'MENSAGENSOPERACOES.DESCRICAO'
    end
  end
  inherited Q_Lotes: TIBQuery
    Left = 535
  end
  inherited P_Lotes: TDataSetProvider
    Left = 535
  end
  inherited C_Lotes: TClientDataSet
    Left = 535
  end
  inherited C_LotesDS: TDataSource
    Left = 535
    Top = 484
  end
  inherited Q_Unidades: TIBQuery
    Top = 195
  end
  inherited C_CFOPs: TClientDataSet
    Left = 391
  end
  inherited P_CFOPs: TDataSetProvider
    Left = 391
  end
  inherited Q_CFOPs: TIBQuery
    Left = 391
  end
  inherited C_CFOPsDS: TDataSource
    Left = 391
    Top = 484
  end
  inherited Q_CSTs: TIBQuery
    Left = 466
  end
  inherited P_CSTs: TDataSetProvider
    Left = 466
  end
  inherited C_CSTs: TClientDataSet
    Left = 467
  end
  inherited C_CSTsDS: TDataSource
    Left = 467
    Top = 484
  end
  inherited Q_Transp: TIBQuery
    Top = 389
  end
  inherited P_Transp: TDataSetProvider
    Left = 22
    Top = 488
  end
  inherited C_Transp: TClientDataSet
    Top = 439
  end
  object C_PlanosPagamentoDS: TDataSource
    DataSet = C_PlanosPagamento
    Left = 865
    Top = 476
  end
  object Q_Precos: TIBQuery
    Database = DMProjeto.DB_Projeto
    Transaction = DMProjeto.IBT_Projeto
    BufferChunks = 1000
    CachedUpdates = False
    Constraints = <
      item
        FromDictionary = False
      end>
    SQL.Strings = (
      
        'Select  '#9'pp.ProdutoPreco, pp.ITEM, pp.TABELAPRECO, pp.PRECO as P' +
        'RECO_NORMAL, '
      #9'pp.PRECOMANUAL, pp.PrecoPromocao, '
      
        #9'tp.DESCRICAO, tp.Baseada, tp.Percentual, i.descricao as descite' +
        'm'
      'From ProdutosPreco pp '
      'INNER JOIN TabelasPreco tp ON pp.TabelaPreco = tp.TabelaPreco'
      'INNER JOIN Itens i on i.item = pp.item'
      
        'Where pp.ITEM  = :ITEM and pp.Unidade = :Unidade and tp.Desativa' +
        'do = '#39'N'#39
      'Order by tp.Percentual, tp.TabelaPreco ')
    UniDirectional = True
    Left = 802
    Top = 172
    ParamData = <
      item
        DataType = ftUnknown
        Name = 'ITEM'
        ParamType = ptUnknown
      end
      item
        DataType = ftUnknown
        Name = 'Unidade'
        ParamType = ptUnknown
      end>
  end
  object P_Precos: TDataSetProvider
    DataSet = Q_Precos
    Constraints = True
    Left = 802
    Top = 219
  end
  object C_Precos: TClientDataSet
    Aggregates = <>
    Params = <>
    ProviderName = 'P_Precos'
    OnCalcFields = C_PrecosCalcFields
    OnFilterRecord = C_ProdutosPrecoFilterRecord
    Left = 803
    Top = 266
    object IntegerField2: TIntegerField
      FieldKind = fkInternalCalc
      FieldName = '_icSelecionado'
    end
    object C_PrecosPRODUTOPRECO: TIntegerField
      FieldName = 'PRODUTOPRECO'
      Required = True
    end
    object C_PrecosITEM: TIntegerField
      FieldName = 'ITEM'
    end
    object C_PrecosTABELAPRECO: TIntegerField
      FieldName = 'TABELAPRECO'
    end
    object C_PrecosPRECOMANUAL: TStringField
      FieldName = 'PRECOMANUAL'
      Size = 1
    end
    object C_PrecosPRECOPROMOCAO: TBCDField
      FieldName = 'PRECOPROMOCAO'
      Precision = 18
      Size = 3
    end
    object C_PrecosDESCRICAO: TStringField
      FieldName = 'DESCRICAO'
      Size = 25
    end
    object C_PrecosBASEADA: TStringField
      FieldName = 'BASEADA'
      Size = 1
    end
    object C_PrecosPERCENTUAL: TBCDField
      FieldName = 'PERCENTUAL'
      Precision = 18
      Size = 2
    end
    object C_PrecosDESCITEM: TStringField
      FieldName = 'DESCITEM'
      Size = 50
    end
    object C_PrecosPRECO_NORMAL: TBCDField
      FieldName = 'PRECO_NORMAL'
      Precision = 18
      Size = 3
    end
    object C_PrecosPRECO: TCurrencyField
      FieldKind = fkInternalCalc
      FieldName = 'PRECO'
    end
  end
  object C_PrecosDS: TDataSource
    DataSet = C_Precos
    Left = 802
    Top = 315
  end
end
